---
title: "R Notebook"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 2
---


# quantifying uncertainty 

```{r}
rnorm(2)
rnorm(2, mean = 5, sd = 1)
rnorm(2, mean = 5, sd = 200)

set.seed(123)
x <-rnorm(100000, mean = 12, sd = 2)
plot(density(x))
#x_s <- c(12, 13, 17)
x_s <- sample(x, 3) 
# x_s <- rnorm(3, mean = 12, sd = 2)
points(x = x_s, y = rep(0.01,3), col = "blue", pch = 5, cex = 2)
abline(v = x_s, col = 'blue', lwd = 2 , lty = 2)
abline(v = mean(x_s), col = 'red', lwd = 4 , lty = 1)
abline(v = c(mean(x_s)-2*sd(x_s), mean(x_s)+2*sd(x_s)), col = 'red', lwd = 1 , lty = 2)



result_list = alist()
for( i in 1:100) {
  x_s <- sample(x, 3) # sample from our x
  result_list[[i]] <- abs( mean(x_s)-mean(x) )  # calculate difference between sample and true mean
}



plot(density(unlist(result_list)), 
     main = "distribution of 3-sample mean deviations from true mean",
     cex.main = 0.7)

plot(ecdf(unlist(result_list)), cex.main = 0.7, cex= 0.5)
abline(h = 0.65, v = 1, col = 'blue')

# 


```

## SEM

```{r}
sample_size <- 3
nsamples <- 1000

sim_data <- matrix(rnorm(nsamples * sample_size, 12, 2), nsamples)
head(sim_data)

sim_data_means <- rowMeans(sim_data)
head(sim_data_means)
hist(sim_data_means, freq = F)
abline(v=12, col = 'red', lwd=4)
x <-rnorm(100000, mean = 12, sd = 2 / sqrt(sample_size))
lines(density(x))

sd(sim_data_means)
sem = 2 / sqrt(sample_size)
sem
```

# ECDF & quantiles


```{r}

n = 1000

showQuantiles <- data.frame(rnorm = sort(rnorm(n)))
showQuantiles$quantile <- round(seq(0,1, length.out = nrow(showQuantiles)), digits = 2)
plot(x = showQuantiles$quantile, y = showQuantiles$rnorm, main = paste0("n = ", n ))
#n <- 10 * n

# ECDF 
plot(y = showQuantiles$quantile, x = showQuantiles$rnorm, main = paste(paste0("n = ", n ), "ECDF"))


```




# confidence intervals

```{r}
# formula for CI = mu +- q(a) * SE
# probably you have seen mean +- 1.96 + SEM? That is the Z quantile for CL = 5%
qnorm(0.975)

###
x_s <- rnorm(100, 12, 2)
s_mean <- mean(x_s)
s_sd <- sd(x_s)
n = length(x_s) 
ci <- qt(0.975, df = n-1)*s_sd/sqrt(n) # formula for confidence limit
ci

boxplot(x_s, ylim = c(5,25))
abline(h = c(s_mean - ci,  s_mean + ci
), col = 'red', lty=2)

abline(h = c(s_mean - s_sd,
             s_mean + s_sd
), col = 'blue', lty=2)

```


# Central limit theorem

```{r}
n=100
replicate(3,hist(runif(n), cex.main = 0.8))
hist(colMeans(replicate(1000, runif(n))), cex.main = 0.8)

```




## Bootstrapping

```{r}
n=5
x <- runif(n, min = 5, max = 6) # single random sample.
b <- replicate(10000, mean(sample(x, replace=TRUE)))


hist(x, main ="one sample", cex.main = 0.8)

hist(replicate(10000, runif(n, min = 5, max =6)), 
     main = "uniform distribution", cex.main = 0.8)

hist(b, main = "bootstrapped" , cex.main = 0.8)

plot(ecdf(b), main = "bootstrapped - cdf" , cex.main = 0.8)

qb <- quantile(b, c(0.025,0.975))
abline(v = qb)

```



# Testing for normality- transformations


```{r}

hist(runif(10000))
shapiro.test(runif(1000))


hist(rnorm(10000))
shapiro.test(rnorm(1000))


```

# Log FC transformation

```{r}
my_data <- data.frame(gene = 0.1 + runif(10000), 
control = 0.1 +runif(10000))
my_data$fold_change <- my_data$gene/my_data$control
hist(my_data$fold_change)
abline(v=1, col = 'red', lwd=2)

hist(log2(my_data$fold_change))
abline(v=0, col = 'red', lwd=2)



```

