---
title: "Assignment 3"
author: "Hans"
date: "9/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
expgrowth = function(timepoint, state, parameters) { 
  with (as.list(c(state, parameters)), {
    dY = a * Y
    list(c(dY)) 
  })
}

pars = c(a = 0.2)
inistate = c(Y = 1)
finish = seq(0, 10, by = 0.1)

library(deSolve)
out = ode(y = inistate, times = finish, func = expgrowth, parms = pars)
plot(out, main = "", ylab = "Y")
out
```


# Excercise 1

```{r}
library(deSolve)

expgrowth = function(timepoint, state, parameters) { 
  with (as.list(c(state, parameters)), {
    dY = a * Y
    list(c(dY)) 
  })
}

pars = c(a = -0.1)
inistate1 = c(Y = 1)
inistate2 = c(Y = 5)
inistate3 = c(Y = 10)
finish = seq(0, 10, by = 0.1)


out1 = ode(y = inistate1, times = finish, func = expgrowth, parms = pars)
out2 = ode(y = inistate2, times = finish, func = expgrowth, parms = pars)
out3 = ode(y = inistate3, times = finish, func = expgrowth, parms = pars)
plot(out1, main = "", ylab = "Y", col = "red")
plot(out2, main = "", ylab = "Y", col = "blue")
plot(out3, main = "", ylab = "Y", col = "black")


#create an empty plot
plot(1, xlab = "time", ylab = "Y ", type = "n", xlim = c(0, 10), ylim = c(min(out3), max(out3)))
 
lines(out1, ylab= "Y = 1", col="blue", lty=2)
lines(out2, ylab= "Y = 5", col="red")
lines(out3, ylab= "Y = 10", col="black")
```


# Exercise 2

```{r}
(finalstate = out1[nrow(out1),2])
```

# Exercise 3

```{r}
(finalstate = out1[nrow(out1),-1])

# Why does the following not work?
(finalstate = out1[-1,-1])
```


# Exercise 4

```{r}
expgrowth = function(timepoint, state, parameters) { 
  with (as.list(c(state, parameters)), {
    dY = a * Y
    list(c(dY)) 
  })
}

pars = c(a = 0.1)
inistate1 = c(Y = 1)
finish1 = seq(0, 10, by = 0.1)
out1 = ode(y = inistate1, times = finish1, func = expgrowth, parms = pars)


pars = c(a = -0.01)
inistate1 = out1[nrow(out1),-1]
finish2 = seq(10, 100, by = 0.1)
out2 = ode(y = inistate1, times = finish2, func = expgrowth, parms = pars)

#create an empty plot
(ymin = min(out1[,2], out2[,2]))
(ymax = max(out1[,2], out2[,2]))
plot(1, xlab = "time", ylab = "Y ", type = "n", xlim = c(0, 100), ylim = c(ymin, ymax))
 
lines(out1, ylab = "Y = 1", col="blue", lty=2)
lines(out2, ylab = "Y = 1", col="blue", lty=2)
```


# Exercise 5

```{r}
library("phaseR")

expgrowth = function(timepoint, state, parameters) { 
  with (as.list(c(state, parameters)), {
    dY = a * Y
    list(c(dY)) 
  })
}
pars <- c(a = 0.2)


phaseport = phasePortrait(expgrowth, parameters = pars, ylim = c(-2, 2), points = 10, xlab = "Y", ylab = "dY/dt (a = 1)", state.names = c("Y")) 
grid() 

stab.expgrowth = stability(expgrowth, ystar = 0, parameters = pars, system = "one.dim", state.names = c("Y"))

pars <- c(a = 1)

phaseport = phasePortrait(expgrowth, parameters = pars, ylim = c(-2, 2), points = 10, xlab = "Y", ylab = "dY/dt (a = 1)", state.names = c("Y")) 
grid() 

stab.expgrowth = stability(expgrowth, ystar = 0, parameters = pars, system = "one.dim", state.names = c("Y"))

pars <- c(a = 10)

phaseport = phasePortrait(expgrowth, parameters = pars, ylim = c(-2, 2), points = 10, xlab = "Y", ylab = "dY/dt (a = 10)", state.names = c("Y")) 
grid() 

stab.expgrowth = stability(expgrowth, ystar = 0, parameters = pars, system = "one.dim", state.names = c("Y"))

pars <- c(a = 0.10)

phaseport = phasePortrait(expgrowth, parameters = pars, ylim = c(-2, 2), points = 10, xlab = "Y", ylab = "dY/dt (a = 0.10)", state.names = c("Y")) 
grid() 

stab.expgrowth = stability(expgrowth, ystar = 0, parameters = pars, system = "one.dim", state.names = c("Y"))

pars <- c(a = 0.010)

phaseport = phasePortrait(expgrowth, parameters = pars, ylim = c(-2, 2), points = 10, xlab = "Y", ylab = "dY/dt (a = 0.010)", state.names = c("Y")) 
grid() 

stab.expgrowth = stability(expgrowth, ystar = 0, parameters = pars, system = "one.dim", state.names = c("Y"))

pars <- c(a = -1)

phaseport = phasePortrait(expgrowth, parameters = pars, ylim = c(-2, 2), points = 10, xlab = "Y", ylab = "dY/dt (a = -1)", state.names = c("Y")) 
grid() 

stab.expgrowth = stability(expgrowth, ystar = 0, parameters = pars, system = "one.dim", state.names = c("Y"))


pars <- c(a = -5)

phaseport = phasePortrait(expgrowth, parameters = pars, ylim = c(-2, 2), points = 10, xlab = "Y", ylab = "dY/dt (a = -5)", state.names = c("Y")) 
grid() 

stab.expgrowth = stability(expgrowth, ystar = 0, parameters = pars, system = "one.dim", state.names = c("Y"))
```


# Question 6


```{r}
expgrowth1 = function(timepoint, state, parameters) { 
  with (as.list(c(state, parameters)), {
    dX = b + k1 * X - k2 * X
    list(c(dX)) 
  })
}


pars = c(b = 5, k1 = 0.5, k2 = 0.1)
inistate = c(X = 1)
finish = seq(0, 10, by = 0.1)

library(deSolve)
out1 = ode(y = inistate, times = finish, func = expgrowth1, parms = pars)

plot(out1, main = "", ylab = "X")
```


# Question 7


# Question 8


# Question 9


# Question 10


```{r}


expgrowth2 = function(timepoint, state, parameters) { 
  with (as.list(c(state, parameters)), {
    dX = b + k1 * X - k2 * X^2
    list(c(dX)) 
  })
}

pars = c(b = 5, k1 = 0.5, k2 = 0.1)
inistate = c(X = 1)
finish = seq(0, 10, by = 0.1)

library(deSolve)
out2 = ode(y = inistate, times = finish, func = expgrowth2, parms = pars)

plot(out2, main = "", ylab = "X")
```


# Question 11


```{r}

library(deSolve)

expgrowth2 = function(timepoint, state, parameters) { 
  with (as.list(c(state, parameters)), {
    dX = b + k1 * X - k2 * X^2
    list(c(dX)) 
  })
}

pars = c(b = 5, k1 = 0.5, k2 = 0.1)
finish = seq(0, 10, by = 0.1)

for (state in c(1, 10, 0.1, 100) ) {
  inistate = c(X = state)
  out2 = ode(y = inistate, times = finish, func = expgrowth2, parms = pars)
  plot(out2, main = "", ylab = "X")
}


inistate = c(X = 20)
out2 = ode(y = inistate, times = finish, func = expgrowth2, parms = pars)
plot(out2, main = "", ylab = "X")

inistate = c(X = 100)
out2 = ode(y = inistate, times = finish, func = expgrowth2, parms = pars)
plot(out2, main = "", ylab = "X")

```
