title: "R Notebook"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 2
---


# Quantifying uncertainty 

```{r}

# Generate two normal sampes, with mu = 0, sd = 1 
rnorm(2)

# Generate two normal sampes, specified mu and sd 
rnorm(2, mean = 5, sd = 1)
rnorm(2, mean = 5, sd = 200)

# Generate 100000 samples
# Specifying the seed ensures repeatability  
set.seed(123)
x <-rnorm(100000, mean = 12, sd = 2)

# Plot density distribution of the 100000 points
# Creating a 'theoretical' normal curve 
plot(density(x))

# Now draw a sample of 3 points somewhere from the 100000 points 
x_s <- sample(x, 3) 

# Plot the samples.
# The x values are the sample, the y values are set to 0.01
# Points are drawn as blue diamonds

points(x = x_s, 
       y = rep(0.01, 3), 
       col = "blue", 
       pch = 5, 
       cex = 2)

# Draw blue dotted vertical lines at the sample points 
abline(v = x_s, col = 'blue', lwd = 2 , lty = 2)

# Draw a red solid vertical line at the mean
abline(v = mean(x_s), col = 'red', lwd = 4 , lty = 1)

# Draw two red vertical dotted lines at mu - 2*sd and mu + 2*sd
abline(v = c(mean(x_s)-2*sd(x_s), mean(x_s)+2*sd(x_s)), 
       col = 'red', lwd = 1 , lty = 2)


# Now draw 100 samples
# Calculate the difference between these samples of 3
# Calculate the difference between tge meand and the true mean

result_list = alist()
for (i in 1:100) {
  x_s <- sample(x, 3) # sample from our x
    result_list[[i]] <- abs( mean(x_s)-mean(x) )  
}

# The density distribution of these mean differences is approximateky normal
# The cex parameter sets the size of the font 
plot(density(unlist(result_list)), 
     main = "Distribution of 3-sample mean deviations from true mean",
     cex.main = 0.7)

# The emperical cumulative distrubution curve 
# Draw a vertical line at 1 ad a horizontal line at 0.65
plot(ecdf(unlist(result_list)), cex.main = 0.7, cex= 0.5)
abline(h = 0.65, v = 1, col = 'blue')

```

## SEM

```{r}
sample_size <- 3
nsamples <- 1000

# Generate 'sample_size * nsamples' and put themm in a matrix
# In fact you generate 1000 samples of size 3 
sim_data <- matrix(rnorm(nsamples * sample_size, 12, 2), nsamples)
head(sim_data)

# Of each sample calculate the mean.
# Plot these points in a histogram
sim_data_means <- rowMeans(sim_data)
head(sim_data_means)
hist(sim_data_means, freq = F)

# Overlay it with a 'theoretical' normal distriubution
abline(v = 12, col = 'red', lwd=4)
x <-rnorm(100000, mean = 12, sd = 2 / sqrt(sample_size))
lines(density(x))

sd(sim_data_means)
sem = 2 / sqrt(sample_size)
sem
```

# ECDF & quantiles


```{r}

n = 1000

# Creat a dataframe with 1 column with 1000 normal samples
# The samples are sorted
showQuantiles <- data.frame(rnorm = sort(rnorm(n)))

# Add a column to the dataframe
# The column contains a seq of 1000 points divided by 1 and rounded to 2 
showQuantiles$quantile <- round(seq(0, 1, length.out = nrow(showQuantiles)), 
                                digits = 2)

# The curve is plotted
plot(x = showQuantiles$quantile, 
     y = showQuantiles$rnorm, 
     main = paste0("n = ", n ))


# The ECDF (Empirical Cumulative Distribution Function) is constructed by swapping the axes 
plot(y = showQuantiles$quantile, 
     x = showQuantiles$rnorm, 
     main = paste(paste0("n = ", n ), "ECDF"))


```




# Confidence intervals

```{r}

# Formula for CI = mu +- q(a) * SE
# Probably you have seen mean +- 1.96 + SEM? That is the Z quantile for CL = 5%

qnorm(0.975)

# Generate 100 samples with mu = 12 and sd 2
x_s <- rnorm(100, 12, 2)

# Calculate the mean and sd of that 100 values
s_mean <- mean(x_s)
s_sd <- sd(x_s)
n = length(x_s) 

# Formula for confidence limit
ci <- qt(0.975, df = n - 1) * s_sd/sqrt(n) 
ci

# Create a boxplot for the samples 
boxplot(x_s, ylim = c(5,25))

# Draw in red lines for the confidence interval
abline(h = c(s_mean - ci,  s_mean + ci), col = 'red', lty=2)

# And blue lines for the mean +/- sd
abline(h = c(s_mean - s_sd, s_mean + s_sd), col = 'blue', lty=2)

```


# Central limit theorem

```{r}
n=100
replicate(3,hist(runif(n), cex.main = 0.8))
hist(colMeans(replicate(1000, runif(n))), cex.main = 0.8)

```




## Bootstrapping

```{r}
n=5
x <- runif(n, min = 5, max = 6) # single random sample.
b <- replicate(10000, mean(sample(x, replace=TRUE)))


hist(x, main ="one sample", cex.main = 0.8)

hist(replicate(10000, runif(n, min = 5, max =6)), 
     main = "uniform distribution", cex.main = 0.8)

hist(b, main = "bootstrapped" , cex.main = 0.8)

plot(ecdf(b), main = "bootstrapped - cdf" , cex.main = 0.8)

qb <- quantile(b, c(0.025,0.975))
abline(v = qb)

```



# Testing for normality- transformations


```{r}

# A uniform distribution is not expected to meet the shapiro test 
hist(runif(10000))
shapiro.test(runif(1000))


hist(rnorm(10000))
shapiro.test(rnorm(1000))


```

# Log FC transformation

```{r}
my_data <- data.frame(gene = 0.1 + runif(10000), 
control = 0.1 +runif(10000))
my_data$fold_change <- my_data$gene/my_data$control
hist(my_data$fold_change)
abline(v=1, col = 'red', lwd=2)

hist(log2(my_data$fold_change))
abline(v=0, col = 'red', lwd=2)
```

