---
title: "First Assignment"
author: "Hans"
date: "9/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("pacman")) +
  install.packages("pacman") 
library(pacman)
```

```{r}
getwd()
15+2
```


# Exercise 6
```{r Exercise 6}
#x1 <- seq(0, 2 * po, 0.01)
po <- 3.141593
x2 <- seq(1, 2 * po, 0.01)
x3 <- seq(0, 2 * pi, 0.01)
y <- sin(x3)
plot (x=x3, y = y)  # This gives a very thick line
plot (x=x3, y = y, type = 'l')  # This gives a nice thin line
plot (x=x3, y = y, type = 'l', main = 'x3')  # This adds a title

```


# Exercise 7

```{r Exercise 7}
1 + 1
1 - 1
1 * 1
1 / 1
```



# Exercise 8 + 9

```{r Exercise 8 + 9}
# '1' + 1   # This will not work and the chunck will break 
as.integer('1') + 1
class(1)
class("1")

```


# Exercise 10

```{r Exercise 10}
1 == 1
1 == 2
1 < 2
(1 != 2)
!(1 == 1)
(1 == 1) || (1 == 2)
(1 == 1) && (1 == 2)
(1 == 1) & (1 == 2)

# pairewise boolean operators
c(TRUE, TRUE, FALSE, TRUE) | c(TRUE, TRUE, TRUE, FALSE) # | means element wise or 
c(TRUE, TRUE, FALSE, TRUE) & c(TRUE, TRUE, TRUE, FALSE) # & means element wise and

```



# Exercise 11

```{r Exercise 11}
my_awesome_function <- function(x) {
  my_awesome_variable <- x
  return(my_awesome_variable)
}

my_awesome_function(1)
my_awesome_function(1+2)
my_awesome_function("tralala")


```

# Exercise 12

```{r}
a <- 1

myfun <- function(dat) {
  a <- 2
  y <- dat + a
  return(y)
}

y = myfun(5)
y
y + a
```


# Exercise 13

If you add two vectors of unequal length, the shorter one is repeated as much as necessary

```{r}
v1 <- seq(1:10)
v2 <- seq(1:2)
v3 <- seq(1:9)
v1
v2
v1 + v2
v1
v3
v1 + v3
```


# Matrices

```{r}
(my_matrix <-  matrix (1:25, 5))
(my_matrix <-  matrix (1:25, 4))
my_matrix <-  matrix (1:25, 5)
my_matrix
my_matrix[3,]
my_matrix[,4]
my_matrix[2:3,2:3]
my_matrix[c(1,4), 2:3]
```



# Data frames

```{r}
my_dataframe <- data.frame(
  my_sentence = c("Snow ", "King ", ", ", "North", " the", "!", "John", "of "), 
  some_numbers = sample(1:100, 8)) 
my_dataframe
my_dataframe[2,1]
my_dataframe$my_sentence
my_dataframe$my_sentence[2]
my_dataframe$some_numbers
lapply(my_dataframe, class)
```


# Exercise 14

```{r}
sentence <- my_dataframe$my_sentence[c(7,3,2,8,5,1,6,4)]
sentence
```


# Lists

(Not clear why you need to use double brackets)

```{r}
my_list <- list()
my_list[[1]] <- 1:5
my_list[[2]] <- my_dataframe$my_sentence
my_list[[3]] <- TRUE
my_list[[4]] <- 'test'

my_list[[3]]
my_list[3]

my_list[[4]]
my_list[4]

my_list[[2]][2]
class(my_list)
class(my_list[[1]])
class(my_list[1])
```


# Exercise 15

```{r}
rfun <- function(a, b) {
  sum = a + b
  res = list(result = sum, a = a, b = b)
  return(res)
}
  
r = rfun(3,5)  
r

```


# Control flow

```{r}
my_other_vector <- 1:7
if (length(my_other_vector) > 8) {
  print("Your vector has more than 8 elements")
} else {
  print("Your vector has 8 or fewer elements")
}
```


# Exercise 16

```{r}
my_awesome_function <- function(x) {
  y <- x + 44 
  if (y > 50) {
    print("Threshold reached:")
    print(y) } 
  else {
    print("To low to reach threshold")
    print(y) 
  }
}

my_awesome_function(5) 
my_awesome_function(10)
```


# Exercise 17

```{r}
age_fun <- function(age) {
  if (age < 2) {
    print('Baby')
  }
  else if (age < 9) {
    print('Kid')
  }
  else if (age < 20) {
    print ('Teenager')
  }
  else {
      print('Adult')
  }
}

age_fun(1)
age_fun(4)
age_fun(13)
age_fun(26)
```


# Exercise 18

```{r}
people_in_tox <- c('Bob', 'Erik', 'Joost', 'Sylvia', 'Gerhard', 'Hans', 'Chantal') 
for (p in people_in_tox) {
  print (p)
}
```

# Exercise 19

```{r}
my_vector = c(1, 4, 50, 100) 

for (value in my_vector) {
  print(value) 
}

for (i in 1:length(my_vector)) { 
   print(my_vector[i])
}

for (i in 1:length(people_in_tox)) { 
  print(people_in_tox[1:i])
}
```


# Example laply

```{r}
say_hi_to <- function(name) {
  print(paste("Hi,", name))
}

people_in_tox <- c('Bob', 'Erik', 'Joost', 'Sylvia', 'Gerhard', 'Hans', 'Chantal') 

lapply(people_in_tox,say_hi_to)

```


Exercise 22

```{r}
if (!require("readr")) {
  install.packages("readr") 
}
library(readr)
if (!require("stringr")) {
  install.packages("stringr") 
}
library(stringr)

data("iris")
iris
d = getwd()
file <- str_c(d, '/csvfile.csv')
write_csv(iris, file, na = "NA", append = FALSE, col_names = TRUE)

my_loaded_iris_data = read_csv(file)
my_loaded_iris_data
```



