---
title: "ICT Assignment 6 Statistics 2"
author: "Hans"
date: "9/13/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
```

## Exercise 1

```{r}
sleep
t.test(data = sleep, extra ~ group, alternative = 'two.sided', paired = FALSE)
t.test(data = sleep, extra ~ group, alternative = 'two.sided', paired = TRUE)

```

## Exercise 2

```{r}
plot(extra ~ group, data = sleep)

p <- sleep %>% 
  ggplot(aes(extra, ID)) + 
  geom_boxplot() + 
  theme_minimal(base_size = 15)
p 


```


# Exercise 3

```{r}
#glimpse(iris)

an1 = aov(data = iris, formula = Sepal.Length ~ Species)
an2 = aov(data = iris, formula = Petal.Length ~ Species)
an3 = aov(data = iris, formula = Sepal.Width ~ Species)
an4 = aov(data = iris, formula = Petal.Width ~ Species)

an1 = aov(data = iris, formula = Sepal.Length ~ Species)
an2 = aov(data = iris, formula = Petal.Length ~ Species)
an3 = aov(data = iris, formula = Sepal.Width ~ Species)
an4 = aov(data = iris, formula = Petal.Width ~ Species)

par(mfrow=c(2,2))
plot(an1, which=1)
plot(an2, which=1)
plot(an3, which=1)
plot(an4, which=1)
par(mfrow=c(1,1))

```


# Exercise 4

```{r}

glimpse(ChickWeight)

# Just the effect of diet
model_lm_d   = lm(data = ChickWeight, formula = weight ~ Diet)

# Just the effect of time
model_lm_t   = lm(data = ChickWeight, formula = weight ~ Time)

# Combined effects of time and diet - the second one considers interaction
model_lm_dt1 = lm(data = ChickWeight, formula = weight ~ Diet + Time)
model_lm_dt2 = lm(data = ChickWeight, formula = weight ~ Diet * Time)

# Only plot the Residuals vs Fitted (which = 1)
par(mfrow=c(2,2))
plot(model_lm_d, which = 1)
plot(model_lm_t, which = 1)
plot(model_lm_dt1, which = 1)
plot(model_lm_dt2, which = 1)
par(mfrow=c(1,1))

summary(model_lm_d)
summary(model_lm_t)
summary(model_lm_dt1)
summary(model_lm_dt2)

# With anova you can compare models

# Consider diet is a lot less effective than considering time
anova(model_lm_d, model_lm_t)

# Considering in addition time makes a big improvemen
anova(model_lm_d, model_lm_dt1)
anova(model_lm_d, model_lm_dt2)

# There is limited improvement over de simple t model
# In oher words just c considering the time already helps a lot
anova(model_lm_t, model_lm_dt1)
anova(model_lm_t, model_lm_dt2)

# The interaction model is best
anova(model_lm_dt1, model_lm_dt2)

# Just to test what happens if you supply the same models
anova(model_lm_d, model_lm_d)

# OK, so model model_lm_dt2 is superior

# Generate new data for extrapolation purposes
new_data <- data.frame(Time = rep(c(50,100,150,365), 4), 
                       Diet = rep(as.factor(1:4), each = 4))
new_data

# Extrapolate and add to new_data
p = predict(model_lm_dt2, new_data)
new_data <- cbind(new_data, p)
new_data <- new_data %>% rename(weight = p)



library(modelr)
inter <- ChickWeight %>%
  data_grid(Diet) %>%
  crossing(Time = 1:5) %>%
  add_predictions(model_lm_dt2, var = "weight")
  #gather_predictions(model_lm_dt2,model_lm_dt1, .pred = "weight")

fancy_data <- tribble(
  ~type, ~data,
  "inter", inter,
  "extra", new_data
) %>% unnest()

# Show the plot for Chick 1 
chick1 = filter(ChickWeight, Chick == 1)
ggplot(data=chick1,aes(x=Time, y=weight)) +
  geom_line() +
  geom_point(data = fancy_data, mapping = aes(color = type), size = 3) +
  scale_x_continuous(trans = "log2")


new_data <- data.frame(Time = c(1), 
                       Diet = c(as.factor(15))
p = predict(model_lm_dt2, new_data)
p
```




# Exercise 5

```{r}
(p <- ggplot(data = ChickWeight, aes(x = Time, y = weight, color = Diet)) + 
   geom_point() + 
   geom_smooth(aes(group = Diet), se = F) + 
   theme_minimal())
```


# Exercise 6

```{r}
data <- read.table('http://bit.ly/2mcJ2TP', header = FALSE)
glimpse(data)
pairs(data)
fit <- lm(V1 ~ . - 1, data = data)
fit
plot(fit)
```

