---
title: "Plotting"
author: "Hans"
date: "9/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pacman)
p_load(tidyverse)
p_load(nycflights13)
theme_set(theme_minimal())
```



# Exercise 1

```{r}
glimpse(iris)
plot(iris)
```


# Exercise 2

```{r}
plot(x=iris$Sepal.Length, y=iris$Sepal.Width)
abline(3.5, -0.1, col = 'red', lwd = 3)

vecFun <- function (input_vector, intercept, slope) { 
  y <- intercept + slope*input_vector 
  return(y) 
}

line_to_plot<-vecFun(iris$Sepal.Length, intercept = 4, slope = -0.15)

lines(iris$Sepal.Length,line_to_plot)
```


# Exercise 2-1

```{r}
with(iris, plot(Sepal.Length, Sepal.Width))
```

# Exercise 2-2

```{r}
with(iris, plot(Sepal.Length, Species))
```

# Exercise 2-3

```{r}
with(iris, plot(Species, Sepal.Length))
```


# Exercise 3-a Title

```{r}
par(mfrow = c(2,2))
 
hist(iris$Sepal.Length, col = 'red')
hist(iris$Sepal.Width, col = 'green')
hist(iris$Petal.Length, col = 'blue')
hist(iris$Petal.Width, col = 'yellow')
```

# Exercise 3-b

```{r}
par(mfrow = c(2,2))

with(iris, list(
  hist(Sepal.Length, col = 'red'),
  hist(Sepal.Width, col = 'green'),
  hist(Petal.Length, col = 'blue'),
  hist(Petal.Width, col = 'yellow'))
)
```
# Exercise 3-c

```{r}
par(mfrow = c(2,2))
 
plot(density(iris$Sepal.Length), col = 'red')
plot(density(iris$Sepal.Width), col = 'green')
plot(density(iris$Petal.Length), col = 'blue')
plot(density(iris$Petal.Width), col = 'yellow')

```


# Exercise 4 + 5

```{r}
glimpse(ToothGrowth)
head(ToothGrowth)
ggplot(data = ToothGrowth) +
  geom_point(mapping = aes(x = dose, y = len, color = supp)) +
  labs(x = "Dose", y ="Tooth Length", color="Supplement")

```

# Exercise 6-1

```{r}
p <- ggplot(data = ToothGrowth) +
  geom_point(mapping = aes(x = dose, y = len, color = supp))
p + geom_smooth(aes(dose, len, color = supp),
                method = "lm", se = F)
```

# Exercise 6-2

```{r}
p <- ggplot(data = ToothGrowth) +
  geom_point(mapping = aes(x = dose, y = len, color = supp))
p + geom_smooth(aes(dose, len, color = supp),
                method = "lm")
```

# Exercise 7

```{r}
p <- ggplot(data = ToothGrowth) +
  geom_point(mapping = aes(x = dose, y = len, color = supp))
p <- p + geom_smooth(aes(dose, len, color = supp),
                method = "lm")
p + facet_wrap( ~ supp)
```

# Exercise 8-1

```{r}
p <- ggplot(data = ToothGrowth) +
  geom_boxplot(mapping = aes(x = dose, y = len, color = supp))
p + facet_wrap( ~ supp)
```
# Exercise 8-2

```{r}
ggplot(ToothGrowth, 
       aes(x = as.factor(dose), y = len, color = as.factor(dose))) + 
       geom_boxplot() + 
       facet_grid(~ supp) + 
       labs(x = "Dose", color = "Dose", y = "Tooth Length")
 
```


# Exercise 9-a

```{r}
#glimpse(midwest)
numeric_cols <- names(midwest %>% select_if(is_numeric))
p <- ggplot(data = midwest) 
for (y_ax in numeric_cols) {
  p <-  p + geom_col(mapping = aes(x = state, y = y_ax, color = state))
}

# This does not get you there, because you do do not have anything for the facet grid 

#p + facet_grid(ncol = 3 )
```


# Exercise 9-b
```{r}
numeric_cols <- names(midwest %>% select_if(is_numeric))
l_midwest <- gather(data = midwest, key = "Variable", value = "Measurement", numeric_cols)

p <- ggplot(data = l_midwest) 
for (y_ax in numeric_cols) {
  p <-  p + geom_col(mapping = aes(x = state, y = y_ax, color = state))
}
p + facet_wrap(~ Variable)
```


# Exercise 9-c
```{r}
numeric_cols <- names(midwest %>% select_if(is_numeric))
l_midwest <- gather(data = midwest, key = "Variable", value = "Measurement",
                    numeric_cols)

p <- ggplot(data = l_midwest) 
for (y_ax in numeric_cols) {
  datatab = filter(l_midwest, Variable == y_ax)
  p <-  p + geom_col(data = datatab, 
                     mapping = aes(x = state, y = Variable, color = state))
}
p + facet_wrap(~ Variable)
```


# Exercise 9-d

```{r}
glimpse(l_midwest)
head (l_midwest)
l_midwest %>% 
  ggplot(aes(x = Measurement)) + 
  geom_density(aes(color = state, fill = state), alpha = 0.3) + 
  facet_wrap(~ Variable, scales = "free") +
  labs(x="log Value")


```


# Exercise 10
```{r}
l_midwest %>% 
  ggplot(aes(log(Measurement+1))) + 
  geom_density(aes(color = state, fill=state), alpha = 0.3) + 
  facet_wrap(~ Variable, scales = "free")
```

