---
title: "R Notebook"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 2
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# This chunk can be used to set the global chunk options.
#knitr::opts_chunk$set(eval=show.answers, collapse = T)

if (!require("pacman")) install.packages("pacman"); library(pacman)
p_load(tidyverse, cowplot, pracma, modelr)
theme_set(theme_minimal(base_size = 13))
```


# Utility functions

```{r}
dnorm_gg <- function(mean = 0, sd = 1, xaround = 5 * sd) {
  ggplot(data = tibble(x = mean + c(-xaround,xaround)), aes(x)) +
  stat_function(fun = dnorm, n = 101, args = list(mean = mean, sd = sd)) + ylab("") +
  scale_y_continuous(breaks = 0) + 
  theme_minimal() + 
  theme(panel.grid.major.x= element_blank(), 
        panel.grid.minor.x= element_blank()) +
  geom_vline(xintercept = mean)
}

dt_gg <- function(df) {
  ggplot(data = tibble(x = c(-6,6)), aes(x)) +
  stat_function(fun = dt, n = 101, args = list(df = df)) + ylab("") +
  scale_y_continuous(breaks = 0) + 
  theme_minimal() + 
  theme(panel.grid.major.x= element_blank(), 
        panel.grid.minor.x= element_blank()) +
  geom_vline(xintercept = 0)
}

std_err <- function(sample) {
  sd(sample) / sqrt(length(sample)) 
} 
```

# t-test

## one sample

### Manual

```{r Manual test}
# Prepare a  normal distribution plot
p <- dnorm_gg(12, 2)
p

# Take a randon sample of 100 
sample      <- rnorm(100, 12.5, 2)

# Determine the mean, sd and sem
sample_mean <- mean(sample)
sample_sd   <- sd(sample)
sample_sem  <- sd(sample) / sqrt(length(sample))

# The plot looks the same but the spread is much less because you use the SEM
# Draw in that plot the mean of the sample
p <- dnorm_gg(12, sample_sem) + 
  geom_vline(xintercept = sample_mean, color = "blue")
p

# Calculate where cut-off should be for the 95% interval
cutoff <- qnorm(0.975, mean = 12, sd = sample_sem)

p <- p + geom_vline(xintercept = cutoff, color = "red")
p

# If the blue line (the measured value) lies to the right of the red one (the limit) you
# reject the nukl hypothesis: given the mean that you find the population distribution cannit
# have been rnorm(100, 12, 2)
```



### Normalised, manual using z-scores

```{r Normalised, manual using z-scores}

# You can use 12 here, because that was a number in the H0 hypothesis 
sem = std_err(sample)
(zscore = (sample_mean - 12) / std_err(sample))
(cl95 <- qnorm(0.975))

p <- dnorm_gg()
p <- p + geom_vline(aes(xintercept = x), data = tibble(x = c(-cl95, cl95)), color = "red")
p <- p + geom_vline(xintercept = zscore, color = "blue")
p
```


### Manual using t-values

```{r}

# Generate a 16 sample set and plot it. Because you have so few values you get a unusual shape,
# much different than a normal distribution
sample <- rnorm(16, 13.5, 2)

ggplot(tibble(x = sample), aes(x)) + 
  geom_density() + geom_vline(xintercept = 12, color = "red")


mu <- mean(sample)
sd <- sd(sample)
degree_freedom = length(sample)-1
sem <- std_err(sample)

# Calculate the normalised tvalue 
tvalue = (mu - 12) / std_err(sample)

# Calculate the limit for 95% confidence (compare to the 1.96 you woukd have found for normal)
clim = qt(.975, df = degree_freedom )

# And compare the two
if (tvalue > clim) {
  cat ("Reject null hypothese, because tvalue ", tvalue, "is larger than limit", clim)
} else {
   cat ("Accept null hypothese, because tvalue ", tvalue, "is smaller than limit", clim)
}

2 * pt(-abs(tvalue), df = degree_freedom) # -abs(tvalue) to get lower tail

(p <- dt_gg(df = degree_freedom))
(p <- p + geom_vline(aes(xintercept = x), data = tibble(x =c(-clim, clim)), color = "red"))
p + geom_vline(xintercept = tvalue, color = "blue")

# Some data as reference  for the following chun=k
mu
mu + c(-clim, clim) * std_err(sample)
sem
degree_freedom
```



### Using t.test 

```{r Using t.test}

# The T test gives exactly the same information

t <- t.test(sample, mu = 12, conf.level = 0.95)
t
t$estimate
t$conf.int
t$stderr
t$parameter
t$p.value

#View(t)
```


## simulation

```{r}
replicate(1e4, t.test(rnorm(16, 12, 2), mu = 12, conf.level = 0.95)$p.value < 0.05) %>% summary()
```


## two sample (bonus)

```{r}

control <- c(4.4, 5.4, 3.8, 5.1)
test <- c(5.5, 5, 6.1, 5.9)

my_data <- data.frame(
  value = c(control, test),
  experiment = rep(c("control", "test"), each = 4)
 )
my_data

plot( my_data$value ~ my_data$experiment)
points(my_data$value ~ my_data$experiment, cex = 2, col = "red")

plot(density(control), ylim = c(0,0.8))
lines(density(test), lty = 2)

t.test(x = control, y = test, var.equal = TRUE)

t_value_function <- function( x, y) {
  t_value <- ( mean(x) - mean(y) ) /  
    ( (sqrt( (var(x) + var(y) )/2)) * sqrt(2 / length(c(x))))
  return(t_value)
  }

t_value <- t_value_function(control, test)
t_value

t_sample <- rt(50000, df = 6)

plot(density(t_sample), main = "theoretical t-distribution with 6 d.f.")
abline(v = t_value)

2 * pt(t_value, df = 6, lower.tail = TRUE)




```


# shape of t distribution

```{r}
(p <- dt_gg(df = 2))
(p <- p + stat_function(fun = dt, n = 101, args = list(df = 5), color = "green"))
(p <- p + stat_function(fun = dt, n = 101, args = list(df = 20), color = "blue"))
(p <- p + stat_function(fun = dnorm, n = 101, color = "red", size = 1))
```


# example t-tests

```{r}
# are there significant wool breaks for wool type A?
t.test( x = warpbreaks$breaks[ warpbreaks$wool == "A"]) # one sample t-test

# are there significantly more than 30 woolbreaks for wool A?
t.test( x = warpbreaks$breaks[ warpbreaks$wool == "A"], mu = 30) # one sample t-test 

# welch t test (unequal variance)
t.test(breaks~wool, data = warpbreaks) # two sample welch t-test

# student t-test equal variance
t.test(breaks~wool, data = warpbreaks, var.equal = TRUE) # two sample t-test

# each person is measured twice, treated with 2 drugs at different/ far away time points
t.test(extra ~ group, data = sleep) # t-test without pairing

t.test(extra ~ group, paired = TRUE, data = sleep) # paired t-test (controling for interindividual differences)
# make sure the ordering of the individuals is the same within both groups.



```



```{r}
set.seed(12554)
adj_p_data <- tibble( 
  sample = LETTERS[1:10], 
  p_value = sample(seq(0.000001,0.1, length.out = 30), 10)
)

adj_p_data %>%
  arrange(p_value) %>%
  mutate(
    rank = row_number(),
    adj_p = p_value * n()/rank,
    adj_p2 = p.adjust(p_value, method = "BH") # alternative method
    )

# see https://support.bioconductor.org/p/41077/ for explanation of duplicate values
```



#Anova
```{r}
anova_model <- aov( breaks ~ tension, data = warpbreaks)
summary(anova_model)

(warpbreaks_vs_others <- warpbreaks %>%
    as_tibble() %>%
    mutate(
      is_L = tension == "L",
      is_M = tension == "M",
      is_H = tension == "H",
    ))

t.test(breaks ~ is_L, data = warpbreaks_vs_others)
t.test(breaks ~ is_M, data = warpbreaks_vs_others)
t.test(breaks ~ is_H, data = warpbreaks_vs_others)
        

TukeyHSD(anova_model)

```


#t.test and anova with linear models

```{r}
warpbreaks %>%
  group_by(tension) %>%
  summarize(mean = mean(breaks))

# identical
anova_model <- aov( breaks ~ tension, data = warpbreaks)
summary(anova_model)

anova_lm <- lm(breaks ~ tension, data = warpbreaks)
summary(anova_lm)

warpbreaks %>%
  group_by(tension) %>%
  summarize(mean = mean(breaks)) %>%
  mutate(mean_diff = mean - first(mean))

# also for t-test
t_t <- t.test( breaks ~ wool, data = warpbreaks, var.equal = TRUE)
t_lm <- lm(breaks ~ wool, data = warpbreaks)

t_t
summary(t_lm)

```

# two way anova

```{r}

model_lm <- lm(breaks ~ wool * tension, data = warpbreaks)
summary(model_lm)

warpbreaks %>%
  group_by(tension) %>%
  summarize(mean = mean(breaks)) %>%
  mutate(mean_diff = mean - first(mean))

warpbreaks %>%
  group_by(wool) %>%
  summarize(mean = mean(breaks)) %>%
  mutate(mean_diff = mean - first(mean))
```


# testing significance of multiple covariates/ factors/ variables

```{r}
model_null <- lm(breaks ~ tension, data = warpbreaks)
summary(model_null)
model_both <- lm(breaks ~ wool + tension, data = warpbreaks)
summary(model_both)
anova(model_both, model_null)

```


# full model & assumptions

```{r}

model_full <- lm(breaks ~ wool * tension, data = warpbreaks)
anova(model_both, model_full )

plot(model_both)

```

# plots

```{r}
library(tidyverse, modelr)
model_null <- lm(breaks ~ tension, data = warpbreaks)
model_both <- lm(breaks ~ wool + tension, data = warpbreaks)
model_full <- lm(breaks ~ wool * tension, data = warpbreaks)
grid <- warpbreaks %>% 
  data_grid(wool, tension) %>% 
  gather_predictions(model_null, model_both,model_full) %>%
  mutate(model = factor(model, 
                        levels = c("model_null", "model_both",
                                   "model_full"), 
                        labels = c("breaks ~ tension", 
                                   "breaks ~ wool+tension", 
                                   "breaks ~ wool*tension"), 
                        ordered = T))
(p <- warpbreaks %>% 
  ggplot(aes(wool, breaks, color = tension)) + 
  geom_boxplot() + 
  theme_minimal(base_size = 15))
p +  geom_line(data = grid, aes(y = pred, group = tension)) + 
  facet_wrap(~ model)
```



